# Generated by Django 4.2.5 on 2023-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_order_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show1',
            field=models.IntegerField(default=0),
        ),
    ]
